name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  main:
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4

      - name: Install dependencies
        run: |
          sudo apt install -yqq libpq-dev
          gem install bundler
      - name: Install gems
        run: |
          bundle install
      - name: Prepare database
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
          RAILS_ENV: test
        run: |
          bundle exec rails db:prepare
      - name: Run rspec tests
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
          RAILS_ENV: test
        run: |
          bundle exec rspec
      - name: Run rubocop
        run: |
          bundle exec rubocop
